### ISSUE TITLE
image_channel为1时，执行main程序会报错

### ISSUE THREAD

**Issue by yancyxu** [z1069614715/pytorch-classifier#1]
**似乎是image_channel并没有动态调整输入模型的权重**
Traceback (most recent call last):
  File "/home/mist/split_b/main.py", line 151, in <module>
    opt, model, ema, train_dataset, test_dataset, optimizer, scaler, lr_scheduler, loss, DEVICE, CLASS_NUM, begin_epoch, best_metrice = parse_opt()
  File "/home/mist/split_b/main.py", line 113, in parse_opt
    model = select_model(opt.model_name, CLASS_NUM, (opt.image_size, opt.image_size), opt.image_channel,
  File "/home/mist/split_b/utils/utils_model.py", line 125, in select_model
    flops, params = profile(model.to(device), (dummy_input,), verbose=False)
  File "/mistgpu/miniconda/envs/test_env/lib/python3.10/site-packages/thop/profile.py", line 212, in profile
    model(*inputs)
  File "/mistgpu/miniconda/envs/test_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mist/split_b/model/resnet.py", line 264, in forward
    return self._forward_impl(x, need_fea)
  File "/home/mist/split_b/model/resnet.py", line 259, in _forward_impl
    x = self.forward_features(x)
  File "/home/mist/split_b/model/resnet.py", line 267, in forward_features
    x = self.conv1(x)
  File "/mistgpu/miniconda/envs/test_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/mistgpu/miniconda/envs/test_env/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/mistgpu/miniconda/envs/test_env/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 1, 448, 448] to have 3 channels, but got 1 channels instead

**Comment by z1069614715** [comment]
不支持通道数为1喔

**Comment by yancyxu** [comment]
如果可以支持灰度图就更好了，单通道图像信息在足以进行图像分类的情况下，会运算的更快

**Comment by z1069614715** [comment]
单通道跟三通道的图像运算，只跟第一层有关系，速度上几乎没有差别
