### ISSUE TITLE
只能跑resnet,训练其他模型时，一直报错。

### ISSUE THREAD

**Issue by loganzhang4** [z1069614715/pytorch-classifier#5]
Traceback (most recent call last):
  File "E:\Git\download\pytorch-classifier-master\main.py", line 151, in <module>
    opt, model, ema, train_dataset, test_dataset, optimizer, scaler, lr_scheduler, loss, DEVICE, CLASS_NUM, begin_epoch, best_metrice = parse_opt()
  File "E:\Git\download\pytorch-classifier-master\main.py", line 113, in parse_opt
    model = select_model(opt.model_name, CLASS_NUM, (opt.image_size, opt.image_size), opt.image_channel,
  File "E:\Git\download\pytorch-classifier-master\utils\utils_model.py", line 59, in select_model
    model = eval('models.{}(pretrained={})'.format(name, pretrained))
  File "<string>", line 1, in <module>
TypeError: 'module' object is not callable
![Uploading P_0LYPL2Y825NUXPY_3[{_8.png…]()

**Comment by loganzhang4** [comment]
![P_0LYPL2Y825NUXPY_3 {_8](https://github.com/z1069614715/pytorch-classifier/assets/114871440/20442cd8-cb2a-4258-8acc-307dfcb2bf71)

**Comment by 174326Jl** [comment]
runs模型下载的链接过期了，可以重新分享一下吗？求求了
